[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'ervandew/supertab'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'rhysd/vim-clang-format'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'justmao945/vim-clang'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'

[[plugins]]
repo = 'kannokanno/previm'
on_ft = 'markdown'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_event = "InsertEnter"
hook_add = '''
'''

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'andymass/vim-matchup'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'


[[plugins]]
repo = 'frigoeu/psc-ide-vim'
on_ft = 'purescript'

[[plugins]]
repo = 'purescript-contrib/purescript-vim'
on_ft = 'purescript'

[[plugins]]
repo = "LumaKernel/coqpit.vim"
on_ft = "coq"

[[plugins]]
repo = "qnighy/satysfi.vim"

[[plugins]]
repo = 'Shougo/vimshell.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows() 
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_mac.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
  '''

[[plugins]]
repo = 'edwinb/idris2-vim'
on_ft = 'idris2'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_add = '''
'''

[[plugins]]
repo = 'mattn/vim-sonictemplate'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_event = 'InsertCharPre'
on_ft = 'snippet'
depends = 'context_filetype.vim'
hook_add = '''
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'


[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
hook_add = '''
'''

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'itchyny/vim-haskell-indent'
on_ft = 'haskell'


[[plugins]]
repo = 'neovimhaskell/haskell-vim'
on_ft = 'haskell'


# debug fsharp
[[plugins]]
repo = 'callmekohei/tigaDebugger'
on_ft = 'fsharp'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'


[[plugins]]
repo = 'ionide/Ionide-vim'
build = 'make fsautocomplete'
on_ft = 'fsharp'

